"""
Verity — Synthesizer Agent
Produces the final, verified research brief with executive summary,
key findings, contradictory evidence, research gaps, limitations, and citations.
Replaces the old ReportAgent.
"""
from __future__ import annotations
from typing import Any, List, TYPE_CHECKING

from .base import BaseAgent
from ..tools.FileEdit import create_document
from ..tools.basetool import list_directory
from ..config import WORKING_DIRECTORY

if TYPE_CHECKING:
    from ..core.language_models import LanguageModelManager
    from ..core.state import State


class SynthesizerAgent(BaseAgent):
    """
    Synthesizer: Reads all verified claims, evidence, and contradictions,
    then produces a clean, traceable research brief in Markdown.

    Every important finding is linked to evidence — no unsupported assertions.
    """

    def __init__(
        self,
        language_model_manager: "LanguageModelManager",
        team_members: List[str],
        working_directory: str = WORKING_DIRECTORY,
    ) -> None:
        super().__init__(
            agent_name="synthesizer_agent",
            language_model_manager=language_model_manager,
            team_members=team_members,
            working_directory=working_directory,
        )

    def _get_tools(self) -> List:
        return [create_document, list_directory]

    def get_state_updates(self, state: "State", output: Any) -> dict[str, Any]:
        """
        Store the generated research brief and write it to disk.
        """
        import os

        content = output if isinstance(output, str) else getattr(output, "content", str(output))

        # If the model returned a well-formed brief, use it directly
        brief = content.strip()

        # Fallback: generate a minimal structured brief from state
        if not brief or len(brief) < 100:
            brief = _build_fallback_brief(state)

        # Write brief to working directory
        try:
            rq = state.research_question
            topic_slug = (
                rq.query[:40].replace(" ", "_").replace("/", "-")
                if rq else "Research"
            )
            filename = f"Research_Brief_{topic_slug}.md"
            filepath = os.path.join(state.working_directory or WORKING_DIRECTORY, filename)
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(brief)
        except Exception:
            pass

        return {"research_brief": brief}


def _build_fallback_brief(state: "State") -> str:
    """Generate a minimal research brief from state when the model output is thin."""
    from ..core.schemas import VerificationStatus

    rq = state.research_question
    question = rq.query if rq else "Research Question"

    passed = [
        c for c in (state.claims or [])
        if c.verification_status == VerificationStatus.PASS
    ]
    failed = [
        c for c in (state.claims or [])
        if c.verification_status == VerificationStatus.FAIL
    ]
    uncertain = [
        c for c in (state.claims or [])
        if c.verification_status == VerificationStatus.UNCERTAIN
    ]

    sources_section = "\n".join(
        f"- [{p.title}]({p.url or '#'}) ({p.year or 'n.d.'})"
        for p in (state.papers or [])
    )
    findings_section = "\n".join(
        f"- {c.statement} *(confidence: {c.confidence_score:.0%})*"
        for c in passed
    )
    contradictions_section = "\n".join(
        f"- {ct.explanation} *(severity: {ct.severity})*"
        for ct in (state.contradictions or [])
    )

    trace = state.execution_trace
    cost_str = f"${trace.total_cost_usd:.4f}" if trace.total_cost_usd else "N/A"
    tokens_str = str(trace.total_tokens) if trace.total_tokens else "N/A"

    return f"""# Research Brief — Verity

## Research Question
{question}

## Executive Summary
This brief summarizes the findings of an automated evidence-grounded research
process. {len(state.papers or [])} sources were reviewed, {len(state.claims or [])} claims
extracted, and {len(passed)} verified.

## Key Findings
{findings_section or '_No verified findings._'}

## Contradictory Evidence
{contradictions_section or '_No contradictions found._'}

## Unverified / Uncertain Claims
{chr(10).join(f'- {c.statement}' for c in uncertain) or '_None._'}

## Rejected Claims
{chr(10).join(f'- {c.statement}' for c in failed) or '_None._'}

## Research Gaps
_Further investigation required where evidence is insufficient or contradictory._

## Limitations
- Results depend on the quality of discovered sources.
- Automated extraction may miss nuance in complex papers.
- Verification is AI-assisted and should be reviewed by domain experts.

## Sources
{sources_section or '_No sources recorded._'}

---
*Generated by Verity · Tokens: {tokens_str} · Estimated cost: {cost_str}*
"""
